name: Lint Check for Functions

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "functions/**"

jobs:
  lint-check-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install
        working-directory: functions

      - name: Run Lint
        run: npm run lint
        working-directory: functions
